version: '3.8'

services:
  api:
    build: .
    container_name: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis

  worker:
    build: .
    container_name: worker
    command: celery -A app.worker.celery worker --loglevel=info
    depends_on:
      - redis
